apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-preferred-app
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: affinity-preferred-app
  template:
    metadata:
      labels:
        app: affinity-preferred-app
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - ssd
                      # - hdd

---
apiVersion: v1
kind: Service
metadata:
  name: affinity-preferred-app-svc
spec:
  selector:
    app: affinity-preferred-app
  ports:
    - port: 8081
      targetPort: 80
  type: LoadBalancer
# kubectl label node minikube disktype=hdd
#kubectl label node minikube disktype=ssd

# kubectl taint node minikube gpu=true:NoSchedule
