apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
        tier: frontend
    spec:
      containers:
        - name: stress-test
          image: polinux/stress
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          command:
            ["stress", "--vm", "1", "--vm-bytes", "256M", "--timeout", "60s"]
# minikube addons enable metrics-server
# kubectl get pods -n kube-system | grep metrics
