apiVersion: apps/v1
kind: Deployment
metadata:
  name: toleration-app
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: toleration-app
  template:
    metadata:
      labels:
        app: toleration-app
        tier: frontend
    spec:
      containers:
        - name: toleration-app
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: toleration-app-svc
spec:
  selector:
    app: toleration-app
  ports:
    - port: 8081
      targetPort: 80
  type: LoadBalancer
# kubectl taint node minikube gpu=true:NoSchedule

# kubectl taint node minikube-m02 gpu=true:NoExecute

# kubectl describe node minikube-m02 | grep -i taint
