apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: "YWRtaW4=" #admin
  password: "cGFzc3dvcmQ=" #password
  database: "d2ViYXBwZGI=" #webappdb

# echo 'webappdb' | base64
# echo 'd2ViYXBwZGIK' | base64 --decode
