apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sql
spec:
  selector:
    matchLabels:
      app: my-sql
  serviceName: my-sql
  replicas: 2
  template:
    metadata:
      labels:
        app: my-sql
    spec:
      volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
      volumeClaimTemplates:
        - metadata:
            name: mysql-pvc
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "fast-storage"
            resources:
              requests:
                storage: 5Gi

      containers:
        - name: my-sql
          image: mysql:5.7
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: database
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: my-sql
spec:
  clusterIP: None # 👈 THIS makes it headless
  selector:
    app: my-sql
  ports:
    - port: 3306
      targetPort: 3306
