apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness
spec:
  containers:
    - name: nginx-liveness
      image: nginx
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10
# kubectl describe po/nginx-liveness
