apiVersion: apps/v1
kind: Deployment
metadata:
  name: labels-app
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: labels-app
  template:
    metadata:
      labels:
        app: labels-app
        tier: frontend
    spec:
      containers:
        - name: labels-app
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      nodeSelector:
        gpu: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: labels-app-svc
spec:
  selector:
    app: labels-app
  ports:
    - port: 8083
      targetPort: 80
  type: LoadBalancer
# kubectl label node minikube-m02 gpu=false

#   kubectl get nodes --show-labels
