# podAntiAffinity → separate pods (HA setup)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noexecute-app
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: noexecute-app
  template:
    metadata:
      labels:
        app: noexecute-app
        tier: frontend
    spec:
      containers:
        - name: noexecute-app
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoExecute"

      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - noexecute-app
              topologyKey: "kubernetes.io/hostname"

      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #             - key: app
      #               operator: In
      #               values:
      #                 - noexecute-app
      #         topologyKey: "kubernetes.io/hostname"

---
apiVersion: v1
kind: Service
metadata:
  name: noexecute-app-svc
spec:
  selector:
    app: noexecute-app
  ports:
    - port: 8082
      targetPort: 80
  type: LoadBalancer
