apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-dev-ns
  namespace: dev
spec:
  hard:
    pods: "1"
    requests.cpu: "2"
    requests.memory: "5Gi"
    limits.cpu: "4"
    limits.memory: "10Gi"
# kubectl get resourcequota resource-quota-dev-ns -n dev
# kubectl describe ns dev

# kubectl describe limitrange limit-range-dev-ns

# kubectl describe namespace dev
